Repository scalar-labs/kelpie-test, pull requests merged in 2021-03, with the labels that each got.

#15 Fix to support Scalar DB 3.0
  scalardb-test/build.gradle
  scalardb-test/src/main/java/kelpie/scalardb/sensor/SensorChecker.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferCommon.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferPreparer.java
Labels: bugfix

#16 Fix without primary key overlap
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferPreparer.java
Labels: bugfix

#17 Make some changes for benchmark of JDBC
  scalardb-test/build.gradle
  scalardb-test/src/main/java/kelpie/scalardb/Common.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/NontransactionalTransferPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/NontransactionalTransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferCommon.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/jdbc/NontransactionalTransferProcessor.java
  scalardl-test/build.gradle
Labels: enhancement

#18 Add Cosmos DB benchmark
  scalardb-test/build.gradle
  scalardb-test/src/main/java/kelpie/scalardb/transfer/cosmos/Account.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/cosmos/CosmosUtil.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/cosmos/NontransactionalTransferPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/cosmos/NontransactionalTransferProcessor.java
  scalardb-test/stored_procedure/upsert.js
Labels: enhancement

#19 Add use_compact_log variable to log less
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferProcessor.java
Labels: improvement
