Repository scalar-labs/kelpie-test, pull requests merged in 2021-12, with the labels that each got.

#39 Add YCSB Benchmark
  scalardb-test/schema/ycsb.json
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/Loader.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadA.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadC.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadF.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/YcsbCommon.java
Labels: enhancement

#46 Batch put in the storage workloads
  scalardb-test/src/main/java/kelpie/scalardb/storage/MultipleClusteringKeyPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/SingleClusteringKeyPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/StorageCommon.java
Labels: improvement

#47 Add a schema file for the transfer workload
  scalardb-test/schema/transfer.json
Labels: improvement

#48 Support config file in Scalar DB test
  scalardb-test/src/main/java/kelpie/scalardb/Common.java
Labels: enhancement

#49 Fix IllegalConfigException in Scalar DB test
  scalardb-test/src/main/java/kelpie/scalardb/Common.java
Labels: bugfix

#50 Handle the CoordinatorException change
  scalardb-test/src/main/java/kelpie/scalardb/Common.java
  scalardl-test/src/main/java/scalardl/transfer/TransferChecker.java
Labels: bugfix

#52 Fix read records for checker
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferCommon.java
Labels: bugfix

#53 Retry when conflict happens in the YCSB workloads
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadA.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadC.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadF.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/YcsbReporter.java
Labels: improvement
