Repository scalar-labs/kelpie-test, pull requests merged in 2023-05, with the labels that each got.

#82 Update base image version of test containers
  scalardb-test/Dockerfile
  scalardl-test/Dockerfile
Labels: bugfix

#80 Add transfer processors for ScalarDB SQL with retry
  scalardb-test/build.gradle
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/SqlCommon.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/TransferPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/TransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/TransferProcessorWithRetry.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/TransferReporter.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/TransferWithTwoPhaseCommitTransactionProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/TransferWithTwoPhaseCommitTransactionProcessorWithRetry.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/jdbc/TransferPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/jdbc/TransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/jdbc/TransferReporter.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/sql/jdbc/TransferWithTwoPhaseCommitTransactionProcessor.java
Labels: enhancement

#81 Refactor scalardb-test
  scalardb-test/src/main/java/kelpie/scalardb/sensor/SensorChecker.java
  scalardb-test/src/main/java/kelpie/scalardb/sensor/SensorProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/MultipleClusteringKeyPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/MultipleClusteringKeyReaderProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/MultipleClusteringKeyWriterProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/NoClusteringKeyPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/NoClusteringKeyReaderProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/NoClusteringKeyWriterProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/SingleClusteringKeyPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/SingleClusteringKeyReaderProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/storage/SingleClusteringKeyWriterProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/NontransactionalTransferPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/NontransactionalTransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferProcessorWithRetry.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferWithTwoPhaseCommitTransactionProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/TransferWithTwoPhaseCommitTransactionProcessorWithRetry.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/WriteSkewTransferChecker.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/WriteSkewTransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/cosmos/NontransactionalTransferPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/cosmos/NontransactionalTransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/dynamo/NontransactionalTransferPreparer.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/dynamo/NontransactionalTransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/graphql/HttpTransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/graphql/HttpTransferProcessorWithRetry.java
  scalardb-test/src/main/java/kelpie/scalardb/transfer/graphql/TransferProcessor.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/Loader.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadA.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadC.java
  scalardb-test/src/main/java/kelpie/scalardb/ycsb/WorkloadF.java
Labels: improvement
